sudo: required
services:
  - docker

before_install:
  - docker build -t niyatidalal/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true niyatidalal/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "frontend"
  env: "frontend-env"
  bucket_name: "elasticbeanstalk-ap-south-1-402100432214"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
